# NumPy first lecture

'! pip install numpy'

- Vector -> 1D
- Matrices -> 2D



In [1]:
! pip install numpy

In [2]:
lst_1 = [1,2,3,4,5,6,7,8,9]
lst_2 = [[1,2,3], [4,5,6,], [7,8,9]]

In [3]:
import numpy as np

In [4]:
arr_2 = np.array(lst_2)
arr_2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
a = np.array([1,3,5,7,9])

In [6]:
np.arange(1,9,2)

array([1, 3, 5, 7])

In [7]:
z = np.zeros((3,4))
z.shape

(3, 4)

In [8]:
z_2 = np.zeros(5)
z_2.shape # note that it is not 1x5, its 5 only 

(5,)

In [9]:
ones = np.ones((4,4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.linspace(1,5, 10) # these values will be evenly spaced


array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [11]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
i = np.random.rand(10,10)

In [13]:
i.max() # get max value
i.argmax() # get index of max value
i.min()  # get of max value
i.argmin()  # get index of max value

np.int64(94)

In [14]:
np.random.randint(10)

2

In [15]:
z.dtype

dtype('float64')

Next is from youtube video from ML roadmap.sh (BroCode YT 1hr numpy)

In [16]:
new_arr = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9],
                    [10,11,2]])

In [17]:
# new_arr[start:stop:step , start:stop:step]

new_arr[1:3,1:]

array([[5, 6],
       [8, 9]])

In [18]:
# Scalar Arithematic

new_arr = np.array([1,2,3])

print(new_arr + 1)
print(new_arr - 2)
print(new_arr * 3)
print(new_arr / 4)
print(new_arr ** 3)

[2 3 4]
[-1  0  1]
[3 6 9]
[0.25 0.5  0.75]
[ 1  8 27]


In [19]:
# Vetorized Math Functions

print(np.square(new_arr))
print(np.ceil(new_arr))

[1 4 9]
[1 2 3]


In [20]:
# Element Wise Arithematic

arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])

print(arr_1 + arr_2)
print(arr_1 - arr_2)
print(arr_1 * arr_2)
print(arr_1 / arr_2)
print(arr_1**arr_2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [21]:
# Boolean Operator Arithematic

scores = np.array([91, 55, 100, 85, 38])
print(scores == 100)
print(scores >= 40)
scores[scores < 40] = 0
print(scores)

[False False  True False False]
[ True  True  True  True False]
[ 91  55 100  85   0]


In [22]:
# Broadcasting

arr_1 = np.array([[1,2,3]])
arr_2 = np.array([[1],[2],[3]])

print(arr_1.shape)
print(arr_2.shape)

print(arr_1 * arr_2)

(1, 3)
(3, 1)
[[1 2 3]
 [2 4 6]
 [3 6 9]]


In [23]:
# Aggregate functions summarize data and typically return a single value

new_arr = np.array([[1,2,3,4],
                    [6,8,9,10]])

print(np.sum(new_arr))
print(np.mean(new_arr))
print(np.std(new_arr))  # for standard deviation
print(np.var(new_arr))  # for variance
print(np.min(new_arr))
print(np.max(new_arr))
print(np.argmin(new_arr))  # min value
print(np.argmax(new_arr))  # max value
print(np.sum(new_arr, axis=0)) # axis=0 is for column and axis=1 is for row column

43
5.375
3.1598061649411346
9.984375
1
10
0
7
[ 7 10 12 14]


In [24]:
# Filtering = Refers to the process of selecting elements
# from an array that match a given condition


ages = np.array([[21, 34, 57, 89, 45],
                 [73, 32, 12, 54, 17]])

teenagers = ages[ages < 18]
adults = ages[(ages >= 18) & (ages < 65)]
seniors = ages[ages >= 65]
evens = ages[ages % 2 == 0]
odds = ages[ages % 2 == 1]
print(teenagers, adults, seniors, evens, odds)

print(np.where(ages > 18, ages, np.nan)) # if you want to preserve the order of the array

[12 17] [21 34 57 45 32 54] [89 73] [34 32 12 54] [21 57 89 45 73 17]
[[21. 34. 57. 89. 45.]
 [73. 32. nan 54. nan]]


In [25]:
# Random numbers generator

rng = np.random.default_rng()

# print(rng.integers(low=1, high=101, size=(2,3))) # out a 2D array of random numbers

# new_arr = np.array([1,2,3,4,5])
# rng.shuffle(new_arr)
# print(new_arr)

fruits = np.array(['apple', 'banana', 'orange', 'mango'])
fruit = rng.choice(fruits, size=(2,3) )
print(fruit)

[['apple' 'banana' 'apple']
 ['apple' 'mango' 'banana']]


In [26]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print("number of dimensions :", arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [27]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [28]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# newarr = arr.reshape(4, 3)
newarr = arr.reshape(2,3,2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [29]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


In [30]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [31]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [32]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]
